apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: test-container
    ports:
    - containerPort: 80    
    volumeMounts:
    - mountPath: /tmp/data
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/data
      # this field is optional
      type: Directory