#A ReplicaSet ensures that a specified number of pod replicas are running at any given time. 
#However, a Deployment is a higher-level concept that manages ReplicaSets and provides declarative updates to Pods 
#along with a lot of other useful features. Therefore, we recommend using Deployments instead of directly using ReplicaSets, 
#unless you require custom update orchestration or don’t require updates at all.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  # Pod definition
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        imagePullPolicy: IfNotPresent